name: SkyPhysicsTest

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      versionString:
        description: 'Version String'
        type: string
env:
  BUILD_TYPE: Release
  PROJECT_NAME: SkyPhysicsTest

jobs:
  build-skse:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - uses: lukka/get-cmake@latest
      
      - name: vcpkg cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "76d153790caf0592fce8fc4484aa6db18c7d00d4"
      - run: rustup update
      - run: | 
              cd ${{github.workspace}}/SkyCloth
              cargo build --release
              cd ..
              move SkyCloth/target/release/SkyCloth.dll ${{github.workspace}}/SkyCloth.dll
              move SkyCloth/target/release/SkyCloth.lib ${{github.workspace}}/SkyCloth.lib
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          configurePreset: ALL
          configurePresetAdditionalArgs: "['-DCMAKE_TOOLCHAIN_FILE:STRING=C:/vcpkg/scripts/buildsystems/vcpkg.cmake']"
          buildPreset: ALL
          buildPresetAdditionalArgs: "['--config Release']"
      - name: Move binaries
        run: |
          cd ${{github.workspace}}/build/Release
          mkdir artifacts
          cd artifacts
          move ../SkyPhysicsTest.dll
          move ../SkyPhysicsTest.pdb
          move ${{github.workspace}}/SkyCloth.dll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: SkyPhysicsTest-1170-DLL
          path: build/Release/artifacts
          retention-days: 90
